#!/usr/bin/python3
"""
    Copyright (C) 2023  Johannes Tobiassen Langvatn, Met Norway

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import os
import logging
import shutil
import subprocess
import sys
from poller_and_downloader import Poller, Downloader
from config_and_logger import init_logging, init_config
from forecaster import forecaster, forecast_archiver

logger = logging.getLogger(__name__)
init_logging(logger)
CONFIG = init_config()
base_path = CONFIG.get("base_path")
ALL_PATH = CONFIG.get("all_path")
ARCHIVE_PATH = CONFIG.get("archive_path")
logger.debug(f"\nAll path is: {ALL_PATH}\nArchive path is: {ARCHIVE_PATH}")

grib_dir = os.path.join(ALL_PATH, "grib")
os.makedirs(grib_dir, exist_ok=True)
dwd_poller = Poller(
    "Anonymous",
    "",
    "",
    main_cycles=CONFIG.get("main_cycles"),
    base_ftp_link="/weather/nwp/v1/m/icon-eu/",
)
reftime, ready = dwd_poller.poll()
logger.info(f"Reftime was found to be {reftime} with status {ready}")
if ready:
    downloaded_files = []
    downloaded = False
    dwd_downloader = Downloader(dwd_poller, grib_dir)
    all_file = os.path.join(ALL_PATH, f"all{reftime}.nc")
    if not os.path.isfile(all_file):
        downloaded_files, downloaded = dwd_downloader.download_and_unzip(reftime)

    if downloaded:
        forecast_file = os.path.join(ALL_PATH, f"forecast_{reftime}.grib2")
        temporary_file = os.path.join(ALL_PATH, f"all{reftime}_tmp.nc")
        logger.info("Catting forecast-gribs")
        with open(forecast_file, "wb") as combined_file:
            for downloaded_file in downloaded_files:
                with open(downloaded_file, "rb") as input_file:
                    shutil.copyfileobj(input_file, combined_file)

        logger.info("Converting from grib to netcdf")
        fimex_environment = os.environ.copy()
        udunits_path = os.path.join(
            sys.prefix, "share", "udunits", "udunits2.xml"
        )
        if os.path.isfile(udunits_path):
            fimex_environment.setdefault("UDUNITS2_XML_PATH", udunits_path)
        subprocess.run(
            [
                "fimex-2.4",
                "--input.file",
                forecast_file,
                "--input.config",
                os.path.join(base_path, "cdmGribReaderConfig.xml"),
                "--output.file",
                temporary_file,
            ],
            check=True,
            env=fimex_environment,
        )
        forecaster(temporary_file, all_file)
        os.remove(temporary_file)
        logger.info(f"Readied the forecast at {all_file}")
        forecast_archiver(all_file, reftime)

    else:
        logger.info("Forecast was ready, but not downloaded")
