#!/usr/bin/python3
"""
    Copyright (C) 2023  Johannes Tobiassen Langvatn, Met Norway

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import os
import logging
import subprocess
from poller_and_downloader import Poller, Downloader
from config_and_logger import init_logging, init_config

logger = logging.getLogger(__name__)
init_logging(logger)
CONFIG = init_config()

base_path = CONFIG.get("base_path")
logger.debug(f"Base path is: {base_path}")
OUTDIR = base_path + "outdir/"
os.makedirs(OUTDIR+"grib", exist_ok=True)
dwd_poller = Poller("Anonymous", "", "", main_cycles=CONFIG.get("main_cycles"))
reftime, ready = dwd_poller.poll()
logger.info(f"Reftime was found to be {reftime} with status {ready}")

if ready:
    DOWNLOADED = False
    dwd_downloader = Downloader(
        dwd_poller, OUTDIR+"grib/")
    if not os.path.isfile(OUTDIR + f"forecast_{reftime}.grib2"):
        DOWNLOADED = dwd_downloader.download_and_unzip(reftime)

    if DOWNLOADED:
        logger.info("Catting forecast-gribs")
        subprocess.run(f"cat {OUTDIR}grib/*{reftime}*.grib2 > {OUTDIR}forecast_{reftime}.grib2",
                       shell=True, check=True)
        logger.info("Converting from grib to netcdf")
        subprocess.run(f"fimex --input.file {OUTDIR}forecast_{reftime}.grib2 --input.config " +
                       f"{base_path}cdmGribReaderConfig.xml --output.file {OUTDIR}all{reftime}.nc",
                       shell=True, check=True)
        dwd_poller.latest_reftime = reftime
    else:
        logger.info("Forecast was ready, but not downloaded")
